Setting:
  DisableEntityVehicleEnter: false
  Shop:
    UpdateTicks: 72000
    MaxPricePercent: 0.25
    MinPricePercent: 0.25
    BuyPriceChangeQuantity: 64
    SellPriceChangeQuantity: 64
    BuyPriceChangePercent: 0.1
    SellPriceChangePercent: 0.1
  Party:
    MaxPlayer: 4
  Dungeon:
    beginning_tower: #dungeon key
      DisplayName: "시작의 탑"
      TotalFloor: 5
      MaxPlayer: 4