Setting:
  DisableEntityVehicleEnter: true
  Shop:
    UpdateSeconds: 3600
    MaxPricePercent: 0.25
    MinPricePercent: 0.25
    BuyPriceChangeQuantity: 64
    SellPriceChangeQuantity: 64
    BuyPriceChangePercent: 0.1
    SellPriceChangePercent: 0.1
  Party:
    MaxPlayer: 4
  Dungeon:
    beginning_tower: #dungeon key
      DisplayName: "시작의 탑"
      TotalFloor: 1
      MaxPlayer: 4
DisableItem:
  - leather_helmet
  - leather_chestplate
  - leather_leggings
  - leather_boots
  - chainmail_helmet
  - chainmail_chestplate
  - chainmail_leggings
  - chainmail_boots
  - iron_helmet
  - iron_chestplate
  - iron_leggings
  - iron_boots
  - golden_helmet
  - golden_chestplate
  - golden_leggings
  - golden_boots
  - diamond_helmet
  - diamond_chestplate
  - diamond_leggings
  - diamond_boots
  - netherite_helmet
  - netherite_chestplate
  - netherite_leggings
  - netherite_boots
  - turtle_helmet