name: TowerRpg
version: '1.0'
main: me.msicraft.towerRpg.TowerRpg
api-version: '1.20'
depend: [MythicMobs, MythicLib, MMOItems, MMOCore, MythicDungeons, Vault]
commands:
  towerrpg:
    description: 'Main commands'

